[package]
name = "lox-interpreter"
version = "0.1.0"
edition = "2021"
authors = ["Christian Venegas"]
description = "Lox interpreter written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
